name: CI-CD Pipeline for MERN App

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to main branch

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted runner (local server)
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Match your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build  # If you have a build step in your MERN app

      - name: Deploy to local server
        run: |
          pm2 stop all  # Stop existing processes
          pm2 start npm --name "mern-app" -- run start  # Start the app using PM2
        env:
          NODE_ENV: production
